### ISSUE TITLE
US 1 | Questions view

### ISSUE THREAD

**Issue by JivanaLipsewers** [JivanaLipsewers/Capstone-90-Fragen-die-verbinden#1]
## Value proposition

As a user
I would like to receive a list of all questions
So that I can get an overview of all questions

## Description

![Image](https://user-images.githubusercontent.com/132828562/251387082-b1a9739d-c991-4290-b5af-033abea042b4.png)

## Acceptance criteria

- [ ] The headline is displayed
- [ ] The category of a question is displayed
- [ ] The question is displayed
- [ ] All questions are listed one below the other, so that the user can find all questions by scrolling down

## Tasks

- [ ] Headline is displayed
- [ ] The category of a question is displayed
- [ ] A question is displayed
- [ ] The available questions are lined up vertically one below the other

**Comment by vaupunkt** [comment]
lgtm :) 
you could display in your preview that there are more than one. is it scaled so only one question is displayed? 
as a tipp: you can use scroll-snap for scrolling - maybe this helps you: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap
