### ISSUE TITLE
US 7 | Game instruction

### ISSUE THREAD

**Issue by JivanaLipsewers** [JivanaLipsewers/Capstone-90-Fragen-die-verbinden#10]

**Comment by JivanaLipsewers** [comment]
## Capstone Game instruction

## Value proposition

As an user
I want a game description
So that I can use the features correctly and play the game 

## Description

![Image](https://github.com/JivanaLipsewers/Capstone-90-Fragen-die-verbinden/assets/132828562/0d41a753-f5ce-4291-ab56-7942f0331e8c)

## Acceptance criteria

- [ ] A guide to the game clarifies necessary questions

## Tasks

- [ ] A subpage is created
- [ ] A headline is displayed
- [ ] A Copytext for the game instructions is displayed
- [ ] A button is displayed
- [ ] The button leads to the questions

**Comment by SelcoD** [comment]
LGTM!
