### ISSUE TITLE
US 8 | Cover

### ISSUE THREAD

**Issue by JivanaLipsewers** [JivanaLipsewers/Capstone-90-Fragen-die-verbinden#11]
## Value proposition

As an user
I want a App Cover
So that I know which app I have just opened

## Description

![Image](https://user-images.githubusercontent.com/132828562/253522252-0f20f4f1-e411-443c-8903-a334bed00a75.png)

## Acceptance criteria

- [ ] When opening the app appears cover

## Tasks

- [ ] A headline is displayed
- [ ] A subheadline is displayed

**Comment by SelcoD** [comment]
LGTM!
