### ISSUE TITLE
US 2 | Filter categories

### ISSUE THREAD

**Issue by JivanaLipsewers** [JivanaLipsewers/Capstone-90-Fragen-die-verbinden#2]
## Value proposition

As an user
I want a filter for categories
So that i can only call questions of a certain category

## Description

![Image](https://user-images.githubusercontent.com/132828562/251412068-b221accb-a37a-445f-ab49-c35d5ccc6081.png)

![Image](https://user-images.githubusercontent.com/132828562/251412092-d7b00219-4ce8-446d-b516-011e4ce0e015.png)

![Image](https://user-images.githubusercontent.com/132828562/251412785-74bb7067-8bb0-4e8d-a7ce-bedfae47f163.png)

## Acceptance criteria

- [ ] A filter field is placed between the headline and the category
- [ ] An icon is placed in the filter field to support accessibility
- [ ] If you open the filter field with a click, all categories are listed below each other
- [ ] Each category gets a checkbox
- [ ] Each category can be selected and deselected by the checkbox
- [ ] Selected categories are positioned on the filter field, which disappears and the categories are displayed horizontally and scrollable side by side
- [ ] The questions are displayed according to the selected category
- [ ] The categories can also be deselected by clicking on them

## Tasks

- [ ] A filter field is added below the headline
- [ ] An icon is added to the filter field to support accecibility
- [ ] The various filter options are added and lined up one below the other
- [ ] The different selectable categories get a checkbox
- [ ] The categories can be selected and deselected again
- [ ] The selected categories can be set to the position of the filter field and are scrollable horizontally
- [ ] The questions sort themselves according to the category
- [ ] The selected filters can also be deselected again by clicking on them

**Comment by RonnySteady** [comment]
Hi Jivana, 

great user story - although the acceptance criteria and the tasks sound very similar.
How about changing the acceptance criteria to be more descriptive and less technical than the tasks?

Maybe like this: 

- the filter field should be easy to find on the page
- also an icon in the field is needed to support accessibility
- the filter field should 
- a click should show all categories listed below each other
- each category can be selected or deselected
- selected categories should be displayed horizontally and scrollable side by side
- the questions are displayed according to the selected category


Cheers, Ronald
