### ISSUE TITLE
US 3 | Add Question

### ISSUE THREAD

**Issue by JivanaLipsewers** [JivanaLipsewers/Capstone-90-Fragen-die-verbinden#3]
## Value proposition

As an user
I want a edit function
So that i can add more questions

## Description

![Image](https://user-images.githubusercontent.com/132828562/251430989-dc0d34fa-7a61-4771-9912-65b75cabb668.png)

![Image](https://user-images.githubusercontent.com/132828562/251430988-72b50690-e1b3-48b8-abdb-946b6c8827bf.png)

## Acceptance criteria

- [ ] A category was added by add category
- [ ] A question was added by add question
- [ ] A question is added via the final button
- [ ] Under the Categories filter, a new category is created at the same time when a new category is created

## Tasks

- [ ] By clicking on "Add Category" a category name can be added
- [ ] By clicking on "Add Question" a question can be added
- [ ] By clicking on the button below the question is finally added
- [ ] Under the Categories filter, a new category is created at the same time

**Comment by CarstenJahnke** [comment]
Very nicely explained! 🚀
