### ISSUE TITLE
US 4 | Add Favorites

### ISSUE THREAD

**Issue by JivanaLipsewers** [JivanaLipsewers/Capstone-90-Fragen-die-verbinden#4]
## Value proposition

As an user
I want a possibility to favorite questions
So that i can quickly find and repeat the questions

## Description

![Image](https://user-images.githubusercontent.com/132828562/251454674-72aa17a5-22cd-4886-8772-d2ef027937a9.png)
![Image](https://user-images.githubusercontent.com/132828562/251454673-1f453429-05fa-4e97-a471-a00f62e506e7.png)

## Acceptance criteria

- [ ] Via a button a question can be favorized or unfavorized 
- [ ] The favorite questions can be selected via a filter

## Tasks

- [ ] Add button with icon at the bottom, next to "add Question
- [ ] Icon turns full color when you click on it and becomes "favorited"
- [ ] The icon turns color when you click on it and becomes a "Favorite".
- [ ] Create "My Favorites" folder in the filter
- [ ] By clicking the "My Favorites" button, Question will be saved to a separate "My Favorites" folder.

**Comment by JessicaLoers** [comment]
**Hi @JivanaLipsewers** ✨, very nice User Story. 

I have some suggestions you could think about. 

------

_A picky one 😬_

As an user
I want a possibility to _mark questions as favorites_
So that i can quickly find and repeat the questions

------

Even if it seems a bit petty, it makes sense that you define your Acceptance Criteria more in detail. Here are some questions that came to mind that I would have as a developer if I had to work an this user story or even as a user. 

- Where or how can I filter for the favorite questions?
- How are these favorited questions displayed?
- How exactly do I recognize as a user that this card is favored?

**Comment by Danielschuetzle** [comment]
LGTM, next time maybe use better color contrast. Wireframe image is a bit hard to read 👍
