### ISSUE TITLE
US 6 | Add notes

### ISSUE THREAD

**Issue by JivanaLipsewers** [JivanaLipsewers/Capstone-90-Fragen-die-verbinden#5]
## Value proposition

As an user
I want a note function
So that i can save exciting answers from players for later

## Description

![Image](https://github.com/JivanaLipsewers/Capstone-90-Fragen-die-verbinden/assets/132828562/116dd2f0-eb19-4801-81c7-1e30de5f3708)

![Image](https://github.com/JivanaLipsewers/Capstone-90-Fragen-die-verbinden/assets/132828562/95766798-e08c-4446-9216-ea34bb34fe7a)

![Image](https://github.com/JivanaLipsewers/Capstone-90-Fragen-die-verbinden/assets/132828562/9b25970c-1e90-482f-9d7b-e5bc76f3c803)

![Image](https://github.com/JivanaLipsewers/Capstone-90-Fragen-die-verbinden/assets/132828562/3a580768-4ec7-47eb-8f38-85fed899f2eb)

## Acceptance criteria

- [ ] A note can be added via a button
- [ ] A note can be added, or canceled again
- [ ] Several notes line up on top of each other

## Tasks

- [ ] Add a button to be able to add a note
- [ ] When you click on the button, the icon changes and fills the whole area 
- [ ] If the button is active, an input field appears above the row of buttons
- [ ] By clicking on the field a note heading and a note can be added
- [ ] By clicking on the x on the left side of the button, or by clicking on the checkmark on the right side of the button, you can add or cancel a note.
- [ ] The notes then line up one above the other
